language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq $EMACS
before_script:
  - $EMACS --version
script: make test emacs=$EMACS
